# Use an official Python runtime as a parent image
FROM public.ecr.aws/docker/library/python:3.12.5-alpine3.19 

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Set environment variable for the message
ENV MESSAGE="Hello, World!"

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run app.py when the container launches
CMD ["python", "app.py"]
