
apiVersion: v1
kind: Service
metadata:
  name: python-web-app-service
spec:
  selector:
    app: python-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer #ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer #ClusterIP

